server:
  port: 8080
spring:
  application:
    name: mt-core-transfers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mt_core_transfers
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
  kafka:
    producer:
      properties:
        schema.registry.url: http://localhost:8081
        allow.auto.create.topics: true
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
topics:
  status-info: mt.transfers.status.info
transfers:
  max-transfer-sum: 100.00
  demo-transfers-enabled: false
  blocked-account-numbers:
    - "123"
    - "234"
    - "456"
integrations:
  limits:
    url: http://localhost:9080/api/v1/limits
    read-timeout: 30s
    write-timeout: 2s