services:
  core-transfers-postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres_custom_ru:latest
    container_name: core-transfers-postgres
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 3
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net

  mt-core-transfers:
    build:
      context: ../../../
      dockerfile: core-transfers/Dockerfile
    image: mt-core-transfers:latest
    container_name: mt-core-transfers
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9590:9590"
    networks:
      - db-net
      - elk-net
      - monitoring-net
      - kafka-net
    depends_on:
      - core-transfers-postgres
      - logstash
      - broker-1
      - broker-2
      - broker-3
      - schema-registry